# Laptop Price Analyzer and Recommendation System

This project analyzes laptop specifications and
prices and recommends laptops based on user
requirements.

### Technologies

- Python
- Numpy 
- Pandas 
- Matplotliblib
- Seaborn 
- Scikit-learn 
- Jupyter Notebook

In [5]:
import numpy as np 
import seaborn as sns
import pandas as pd 
import matplotlib.pyplot as plt

## 1. Creating the Dataset

We will generate a synthetic laptop dataset 
containing specifications such as brand, processor, RAM, storage, GPU, battery life, weight and price.

In [6]:
np.random.seed(42)

number_of_laptops = 300

In [7]:
brands = [
    "Lenovo",
    "HP",
    "Dell",
    "ASUS",
    "Acer",
    "Apple",
    "MSI"
]

processors = [
    "Core i3",
    "Core i5",
    "Core i7",
    "Ryzen 5",
    "Ryzen 7",
    "M1",
    "M2"
]

gpus = [
    "Integrated",
    "GTX 1650",
    "RTX 2050",
    "RTX 3050",
    "RTX 4060"
]

use_cases = [

    "Office",
    "Programming",
    "Design",
    "Gaming",
    "Video Editing"
]

In [8]:
df = pd.DataFrame({
    "brands": np.random.choice(
        brands,
        number_of_laptops
    ),

    "processor": np.random.choice(
        processors,
        number_of_laptops
    ),

    "ram_gb": np.random.choice(
        [4,8,12,32,64],
        number_of_laptops
    ),
    "Storage_gb": np.random.choice(
        [256,512,1024,2028],
        number_of_laptops
    ),

    "gpu": np.random.choice(
        gpus,
        number_of_laptops
    ),

    "screen_size": np.round(
        np.random.uniform(13.3, 17.3,
            number_of_laptops),
            1
    ),

    "battery_hours": np.round(
        np.random.uniform(4,14,
                number_of_laptops),
                1
    ),

    "weight_kg": np.round(
        np.random.uniform(1.2, 3.0,
                          number_of_laptops),
                          1
    ),

    "use_cases": np.random.choice(
        use_cases,
        number_of_laptops
    )        
})

In [9]:
df.head(5)

,brands,processor,ram_gb,Storage_gb,gpu,screen_size,battery_hours,weight_kg,use_cases
0,MSI,Core i7,8,2028,RTX 2050,16.4,8.3,1.7,Design
1,ASUS,Core i5,12,256,Integrated,13.6,13.8,1.7,Design
2,Acer,Core i7,8,512,GTX 1650,16.6,5.5,2.5,Office
3,MSI,M2,4,256,RTX 3050,15.0,8.6,2.7,Gaming
4,Dell,Core i7,64,2028,RTX 2050,17.0,10.8,2.4,Video Editing

In [13]:
processor_score = {
    "Core i3": 1,
    "Core i5":2,
    "Core i7":3,
    "Ryzen 5":2,
    "Ryzen 7":3,
    "M1":3,
    "M2":4
}


gpu_scores = {
    "Integrated":0,
    "GTX 1650":1,
    "RTX 2050":2,
    "RTX 3050":3,
    "RTX 4060":5
}

In [19]:
df["processor_score"] = df["processor"].map(
    processor_score
)


df["gpu_scores"] = df["gpu"].map(
    gpu_scores
)

In [20]:
df.head(5)

,brands,processor,ram_gb,Storage_gb,gpu,screen_size,battery_hours,weight_kg,use_cases,processor_score,gpu_scores
0,MSI,Core i7,8,2028,RTX 2050,16.4,8.3,1.7,Design,3,2
1,ASUS,Core i5,12,256,Integrated,13.6,13.8,1.7,Design,2,0
2,Acer,Core i7,8,512,GTX 1650,16.6,5.5,2.5,Office,3,1
3,MSI,M2,4,256,RTX 3050,15.0,8.6,2.7,Gaming,4,3
4,Dell,Core i7,64,2028,RTX 2050,17.0,10.8,2.4,Video Editing,3,2